// Device Detail Event Codes
const COMPONENT_MSG_EVENT_BASE = 300;
export const EVT_DEVICE_DATA_DISPLAY_APP_DETAILS = COMPONENT_MSG_EVENT_BASE + 1;

// Widget Event Codes
const WIDGET_MSG_EVENT_BASE = 700;
export const EVT_WIDGET_ACTIVE_USERS_UPDATED = WIDGET_MSG_EVENT_BASE + 1;
